development:
  dialect: postgres
  database: ntarikoon_park
  user: hallecraft
  password: manager123
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/ntarikoon_park_test"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/ntarikoon_park_production"}}